import type { NextPage } from "next";
import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useFetch } from "../hooks/api/useFetch";
import { SearchForm } from "../components/Search";
import { ListItem } from "../components/ListItem/ListItem";

const Home: NextPage = () => {
  const [search, setSearch] = React.useState<string>("");
  const { data, refetch, error, isLoading, isFetching } = useFetch(
    "bikes",
    `/search?query=${search}&stolenness=non`,
    {
      enabled: false,
    }
  );
  const onFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    refetch();
  };
  const onSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearch(e.target.value);
  };
  if (isFetching) return <div>Loading...</div>;

  if (error) return <div>An error has occurred: " + error?.message</div>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <SearchForm
          value={search}
          onSubmit={onFormSubmit}
          onSearchChange={onSearchChange}
        />
        {data?.bikes ? (
          <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
            <ul className="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
              {data?.bikes.map(({ id, title, description, thumb }: any) => {
                return (
                  <ListItem
                    key={id}
                    id={id}
                    title={title}
                    description={description}
                    image={thumb}
                  />
                );
              })}
            </ul>
          </div>
        ) : (
          <>No bikes found</>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
